EnablePlayground: true
JWTConfig:
  SecretKey: "e31ce15c-5315-44eb-8a8f-a272924c03fd"
  OperationKey: "6aff45ff-1ffd-473d-9693-f21d8ab84b85"

ListenAddr: 0.0.0.0:8001

TimeOut: 6

LoggerConfig:
  Level: trace

Salt: "6aff45ff-1ffd-473d-9693-f21d8ab84b85"
PostgresConfig:
  Host: 127.0.0.1
  Port: 5432
  User: root
  Password: root
  DBName: gtest